export const iconsUrl = {
  home: "/assets/icons/home.png",
  wallet: "/assets/icons/wallet.png",
  setting: "/assets/icons/setting.png",
  activity: "/assets/icons/activity.png",
  add: "/assets/icons/add.png",
  back: "/assets/icons/back.png",
  menu: "/assets/icons/menu.png",
  plus: "/assets/icons/plus.png",
  notion: "/assets/icons/notion.png",
  dropbox: "/assets/icons/dropbox.png",
  openai: "/assets/icons/openai.png",
  adobe: "/assets/icons/adobe.png",
  medium: "/assets/icons/medium.png",
  figma: "/assets/icons/figma.png",
  spotify: "/assets/icons/spotify.png",
  github: "/assets/icons/github.png",
  claude: "/assets/icons/claude.png",
  canva: "/assets/icons/canva.png",
};